export const categories = [
  { id: 1, label: "Mobile" },
  { id: 2, label: "Clothing" },
  { id: 3, label: "Pharmacy & Health" },
  { id: 4, label: "Vehicles" },
  { id: 5, label: "Flowers and Decor" },
  { id: 6, label: "Glasses & Contact lenses" },
  { id: 7, label: "Movies, Music & Games" },
  { id: 8, label: "Stationary" },
  { id: 9, label: "Home & Garden" },
  { id: 10, label: "Skincare & Cosmetics" },
  { id: 11, label: "Books & Magazines" },
  { id: 12, label: "Sports" },
  { id: 13, label: "Internet & Cellular" },
  { id: 14, label: "Fashion" },
  { id: 15, label: "Travel & Tour" },
  { id: 16, label: "Jewelry" },
  { id: 17, label: "Watches" },
  { id: 18, label: "Office" },
  { id: 19, label: "Eat & Drink" },
  { id: 20, label: "Shoes" },
  { id: 21, label: "Shopping" },
  { id: 22, label: "Toys and Babies" },
  { id: 23, label: "Kitchen" },
  { id: 24, label: "Entertainment" },
  { id: 25, label: "Hotel" },
  { id: 26, label: "Electronics" },
];
